export var companiesResponse = {companies: [
	{id: "10161332", url: "https://api.mattermark.com/companies/10161332", company_name: "startangels.ch", domain: "startangels.ch"}
	,{id: "10161350", url: "https://api.mattermark.com/companies/10161350", company_name: "qvanteq.com", domain: "qvanteq.com"}
	,{id: "10161284", url: "https://api.mattermark.com/companies/10161284", company_name: "ankaramasoz.masajevde.com", domain: "ankaramasoz.masajevde.com"}
	,{id: "10161247", url: "https://api.mattermark.com/companies/10161247", company_name: "wuem.eu", domain: "wuem.eu"}
	,{id: "10161388", url: "https://api.mattermark.com/companies/10161388", company_name: "tozzl.com", domain: "tozzl.com"}
	,{id: "10161302", url: "https://api.mattermark.com/companies/10161302", company_name: "hitmine.fi", domain: "hitmine.fi"}
	,{id: "10168387", url: "https://api.mattermark.com/companies/10168387", company_name: "BuddiezApp.com", domain: "buddiezapp.com"}
	,{id: "10168389", url: "https://api.mattermark.com/companies/10168389", company_name: "drugnews.net", domain: "drugnews.net"}
	,{id: "10168391", url: "https://api.mattermark.com/companies/10168391", company_name: "labs.inqbation.com", domain: "labs.inqbation.com"}
	,{id: "10163186", url: "https://api.mattermark.com/companies/10163186", company_name: "carpetcleaning-bermondsey.co.uk", domain: "carpetcleaning-bermondsey.co.uk"}
]}

export var companyResponse = [
	{
		"id":10168389,
		"website":"#<Models::Website:0x00000007d53278>",
		"company_name":"drugnews.net",
		"location":"washington d.c.",
		"state":"DC",
		"country":"usa",
		"twitter_handle":null,
		"facebook_slug":null,
		"crunchbase_slug":"drugnews",
		"is_raising":null,
		"est_founding_date":null,
		"stage":"no known funding",
		"total_funding":null,
		"last_funding_date":null,
		"last_funding_amount":null,
		"has_mobile":0,
		"employees":null,
		"employees_month_ago":null,
		"employees_6_months_ago":null,
		"cached_growth_score":null,
		"cached_mattermark":0,
		"cached_uniques":401,
		"cached_uniques_week_ago":237,
		"cached_uniques_month_ago":169,
		"cached_mobile_downloads":null,
		"cached_mobile_downloads_week_ago":null,
		"cached_mobile_downloads_month_ago":null,
		"business_models":null,
		"cached_industries":"healthcare, pharmaceuticals",
		"ipos":[],
		"itunes_apps":[],
		"fundings":[],
		"acquired_by":[],
		"acquired_companies":[],
		"employee_counts":[],
		"growth_scores":[
			{"recorded_at":"2015-07-20 00:00:00 UTC", "score":6},
			{"recorded_at":"2015-07-13 00:00:00 UTC", "score":-12},
			{"recorded_at":"2015-07-06 00:00:00 UTC", "score":-12},
			{"recorded_at":"2015-06-29 00:00:00 UTC", "score":-30},
			{"recorded_at":"2015-06-22 00:00:00 UTC", "score":-28},
			{"recorded_at":"2015-06-15 00:00:00 UTC", "score":-31},
			{"recorded_at":"2015-06-08 00:00:00 UTC", "score":-33},
			{"recorded_at":"2015-06-01 00:00:00 UTC", "score":-50},
			{"recorded_at":"2015-05-25 00:00:00 UTC", "score":-71},
			{"recorded_at":"2015-05-18 00:00:00 UTC", "score":-62},
			{"recorded_at":"2015-05-11 00:00:00 UTC", "score":-54},
			{"recorded_at":"2015-05-04 00:00:00 UTC", "score":-54},
			{"recorded_at":"2015-04-27 00:00:00 UTC", "score":-65},
			{"recorded_at":"2015-04-20 00:00:00 UTC", "score":-51},
			{"recorded_at":"2015-04-13 00:00:00 UTC", "score":-46},
			{"recorded_at":"2015-04-06 00:00:00 UTC", "score":-55},
			{"recorded_at":"2015-03-30 00:00:00 UTC", "score":-66},
			{"recorded_at":"2015-03-23 00:00:00 UTC", "score":-78},
			{"recorded_at":"2015-03-16 00:00:00 UTC", "score":-70},
			{"recorded_at":"2015-03-09 00:00:00 UTC", "score":-78},
			{"recorded_at":"2015-03-02 00:00:00 UTC", "score":-104},
			{"recorded_at":"2015-02-23 00:00:00 UTC", "score":-108},
			{"recorded_at":"2015-02-16 00:00:00 UTC", "score":-168},
			{"recorded_at":"2015-02-09 00:00:00 UTC", "score":-178},
			{"recorded_at":"2015-02-02 00:00:00 UTC", "score":-139},
			{"recorded_at":"2015-01-26 00:00:00 UTC", "score":-76},
			{"recorded_at":"2015-01-19 00:00:00 UTC", "score":-122},
			{"recorded_at":"2015-01-12 00:00:00 UTC", "score":-97},
			{"recorded_at":"2014-12-29 00:00:00 UTC", "score":44},
			{"recorded_at":"2014-11-24 00:00:00 UTC", "score":606}
		],
		"description":"No description available.",
		"domain":"drugnews.net",
		"description_plain_text":"", 
		"people":[]
	},
]



export var fundingsResponse = {
  "fundings":[  
    {  
      "id":"2355653",
      "company_id":"10901065",
      "company_name":"Voxel8",
      "investors":"In-Q-Tel, ARCH Venture Partners, Braemar Energy Ventures, Spark Investment Fund",
      "investor_slugs":"InQTel, ARCH, braemar-energy-ventures, spark-investment-fund",
      "series":"a",
      "rounds_funding_date":"2015-07-24",
      "amount":12000000,
      "currency":"USD",
      "news_url":"//3dprintingindustry.com/2015/07/24/voxel8-ceo-jennifer-lewis-on-how-12m-in-funding-will-fuel-the-future-of-electronics-3d-printing/",
      "industry":null,
      "region":"Boston",
      "city":"Somerville",
      "state":"MA",
      "country":"USA",
      "funding_id":"2355653",
      "created_on":"2015-07-24 20:45:07"
    },
    {  
      "id":"2355962",
      "company_id":"11013890",
      "company_name":"Fitternity",
      "investors":"Exfinity Venture Partners",
      "investor_slugs":"exfinity-fund",
      "series":"seed",
      "rounds_funding_date":"2015-07-24",
      "amount":1000000,
      "currency":"USD",
      "news_url":"http://techcrunch.com/2015/07/24/fitternity/",
      "industry":null,
      "region":null,
      "city":"Mumbai",
      "state":null,
      "country":"IND",
      "funding_id":"2355962",
      "created_on":"2015-07-24 18:42:49"
    },
    {  
      "id":"2355975",
      "company_id":"11020124",
      "company_name":"BroEx",
      "investors":"Lightspeed Venture Partners",
      "investor_slugs":"Lightspeed",
      "series":"seed",
      "rounds_funding_date":"2015-07-24",
      "amount":1000000,
      "currency":"USD",
      "news_url":"http://yourstory.com/2015/07/broex-funding/",
      "industry":null,
      "region":null,
      "city":"Gurgaon",
      "state":"Haryana",
      "country":"IND",
      "funding_id":"2355975",
      "created_on":"2015-07-24 19:08:35"
    },
    {  
      "id":"2355976",
      "company_id":"231596",
      "company_name":"AdAgility",
      "investors":"Boston Seed Capital, Tim McSweeney, Todd McSweeney",
      "investor_slugs":"BostonSeedCapital, TimMcSweeney, ToddMcSweeney",
      "series":"seed",
      "rounds_funding_date":"2015-07-24",
      "amount":1600000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/adagility-raises-1-6m-in-funding.html",
      "industry":null,
      "region":"Boston",
      "city":"Waltham",
      "state":"MA",
      "country":"USA",
      "funding_id":"2355976",
      "created_on":"2015-07-24 19:13:04"
    },
    {  
      "id":"2355662",
      "company_id":"233083",
      "company_name":"Dealstruck",
      "investors":"Trinity Ventures",
      "investor_slugs":"Trinity",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":10000000,
      "currency":"USD",
      "news_url":"http://www.xconomy.com/san-diego/2015/04/08/lender-dealstruck-plans-expansion-with-58m-equity-credit-funding/",
      "industry":"Banking,Finance,Lending",
      "region":"San Diego",
      "city":"Carlsbad",
      "state":"CA",
      "country":"USA",
      "funding_id":"2355662",
      "created_on":"2015-04-09 06:21:38"
    },
    {  
      "id":"2355668",
      "company_id":"292484",
      "company_name":"Creopop",
      "investors":"National Research Foundation, Wavemaker Partners",
      "investor_slugs":"national-research-foundation, wavemaker",
      "series":"seed",
      "rounds_funding_date":"2015-07-23",
      "amount":1400000,
      "currency":"USD",
      "news_url":"http://3dprintingindustry.com/2015/06/02/creopop-photopolymer-3d-pen-signs-more-investors/",
      "industry":"Retail",
      "region":null,
      "city":"Singapore",
      "state":null,
      "country":"SGP",
      "funding_id":"2355668",
      "created_on":"2015-06-03 00:06:09"
    },
    {  
      "id":"2355806",
      "company_id":"11019947",
      "company_name":"Sutrovax",
      "investors":"Abingworth, Roche Venture Fund, Longitude Capital, CTI Capital",
      "investor_slugs":"Abingworth, roche-venture-fund, longitude-capital, cti-capital",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":22000000,
      "currency":"USD",
      "news_url":"http://feeds.bizjournals.com/~r/bizj_sanfrancisco/~3/jjI5khNEUm8/sutrovax-vaccines-series-a-abingworth-roche.html",
      "industry":null,
      "region":"Bay Area",
      "city":"San Francisco",
      "state":"CA",
      "country":"USA",
      "funding_id":"2355806",
      "created_on":"2015-07-23 23:20:17"
    },
    {  
      "id":"2355809",
      "company_id":"88702",
      "company_name":"Ginkgo Bioworks",
      "investors":"Felicis Ventures, Y Combinator, OS Fund",
      "investor_slugs":"Felicis, YC, os-fund",
      "series":"b",
      "rounds_funding_date":"2015-07-23",
      "amount":45000000,
      "currency":"USD",
      "news_url":"http://techcrunch.com/2015/07/23/ginkgo-bioworks-takes-on-zymergen-with-45-million-in-series-b-funding/",
      "industry":"Biotechnology",
      "region":"Boston",
      "city":"Boston",
      "state":"MA",
      "country":"USA",
      "funding_id":"2355809",
      "created_on":"2015-07-23 23:23:50"
    },
    {  
      "id":"2355862",
      "company_id":"133092",
      "company_name":"NewsUp",
      "investors":"McLane Group",
      "investor_slugs":"mclane-group",
      "series":"seed",
      "rounds_funding_date":"2015-07-23",
      "amount":500000,
      "currency":"USD",
      "news_url":"http://technical.ly/baltimore/2015/07/23/newsup-500k-equity-round-mclane-group/",
      "industry":"Advertising,Bitcoin,Education,Fashion,Finance,Gaming,Media,Mobile",
      "region":"Baltimore",
      "city":"Baltimore",
      "state":"MD",
      "country":"USA",
      "funding_id":"2355862",
      "created_on":"2015-07-24 00:19:24"
    },
    {  
      "id":"2355864",
      "company_id":"280515",
      "company_name":"Bulletproof Coffee",
      "investors":"Trinity Ventures",
      "investor_slugs":"Trinity",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":9000000,
      "currency":"USD",
      "news_url":"http://venturebeat.com/2015/07/23/bulletproof-the-company-that-puts-butter-in-coffee-just-raised-9m/",
      "industry":null,
      "region":"Los Angeles",
      "city":"Santa Monica",
      "state":"CA",
      "country":"USA",
      "funding_id":"2355864",
      "created_on":"2015-07-24 00:24:42"
    },
    {  
      "id":"2355870",
      "company_id":"6255",
      "company_name":"SpiderOak",
      "investors":"OCA Ventures, DRW Venture Partners, KGC Capital, BW Capital Partners",
      "investor_slugs":"oca-ventures, drw-venture-partners, kgc-capital, bw-capital-partners",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":3500000,
      "currency":"USD",
      "news_url":"http://www.chicagotribune.com/bluesky/originals/ct-spideroak-series-a-bsi-20150723-story.html",
      "industry":"Cloud Computing,Data Storage,Storage",
      "region":"Chicago",
      "city":"Northbrook",
      "state":"IL",
      "country":"USA",
      "funding_id":"2355870",
      "created_on":"2015-07-24 00:26:19"
    },
    {  
      "id":"2355874",
      "company_id":"1017",
      "company_name":"Social Gaming Network",
      "investors":"Netmarble Games",
      "investor_slugs":"netmarble-games",
      "series":"private_equity",
      "rounds_funding_date":"2015-07-23",
      "amount":130000000,
      "currency":"USD",
      "news_url":"http://www.socaltech.com/sgn_raises__3_m_from_netmarble_games/s-0061161.html",
      "industry":"Gaming,Social Networking",
      "region":"Los Angeles",
      "city":"Los Angeles",
      "state":"CA",
      "country":"USA",
      "funding_id":"2355874",
      "created_on":"2015-07-24 00:50:00"
    },
    {  
      "id":"2355876",
      "company_id":"10912652",
      "company_name":"Outpost Games",
      "investors":"Benchmark",
      "investor_slugs":"Benchmark",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":6200000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/outpost-games-closes-6-2m-series-a-funding.html",
      "industry":"Gaming",
      "region":null,
      "city":null,
      "state":null,
      "country":null,
      "funding_id":"2355876",
      "created_on":"2015-07-24 00:41:29"
    },
    {  
      "id":"2355880",
      "company_id":"14022",
      "company_name":"Ra Pharmaceuticals",
      "investors":"New Enterprise Associates, Morgenthaler Ventures, Novo Ventures, Amgen Ventures, Novartis Venture Fund, RA Capital Management, Rock Springs Capital Management, Lightstone Ventures, Limulus Venture Partners",
      "investor_slugs":"NEA, Morgenthaler, novo-ventures, amgen-ventures, NovartisVentureFund, ra-capital management, rock-springs-capital-management, lightstone-ventures, limulus-venture-partners",
      "series":"b",
      "rounds_funding_date":"2015-07-23",
      "amount":58500000,
      "currency":"USD",
      "news_url":"http://www.xconomy.com/boston/2015/07/23/ra-pharma-gets-58-5m-in-crossover-cash-to-target-rare-blood-disease/",
      "industry":"Biotechnology,Healthcare,Pharmaceuticals",
      "region":"Boston",
      "city":"Cambridge",
      "state":"MA",
      "country":"USA",
      "funding_id":"2355880",
      "created_on":"2015-07-24 00:56:21"
    },
    {  
      "id":"2355889",
      "company_id":"42365",
      "company_name":"Leadspace",
      "investors":"Battery Ventures",
      "investor_slugs":"Battery",
      "series":"b",
      "rounds_funding_date":"2015-07-23",
      "amount":18000000,
      "currency":"USD",
      "news_url":"https://www.pehub.com/2015/07/leadspace-scores-18-mln-in-battery-ventures-led-round/",
      "industry":"Enterprise Software,Marketing",
      "region":null,
      "city":"Ramat HaSharon",
      "state":"CA",
      "country":"ISR",
      "funding_id":"2355889",
      "created_on":"2015-07-24 00:57:48"
    },
    {  
      "id":"2355940",
      "company_id":"144509",
      "company_name":"Popular Pays",
      "investors":"Bessemer Venture Partners, Soma Capital, Social Starts, Mike Shinoda, Romar Capital",
      "investor_slugs":"Bessemer, soma-capital, social-starts, MikeShinoda, romar-capital",
      "series":"seed",
      "rounds_funding_date":"2015-07-23",
      "amount":2000000,
      "currency":"USD",
      "news_url":"http://techcrunch.com/2015/07/23/popular-pays-funding/",
      "industry":"Advertising,Bitcoin,Finance,Marketing,Mobile,Social Networking",
      "region":"Chicago",
      "city":"Chicago",
      "state":"IL",
      "country":"USA",
      "funding_id":"2355940",
      "created_on":"2015-07-24 17:37:41"
    },
    {  
      "id":"2355944",
      "company_id":"83478",
      "company_name":"Remedy Systems",
      "investors":"Bain Capital Ventures",
      "investor_slugs":"bain-capital-ventures",
      "series":"b",
      "rounds_funding_date":"2015-07-23",
      "amount":50000000,
      "currency":"USD",
      "news_url":"https://www.pehub.com/2015/07/remedy-partners-raises-50-mln-from-bain-capital-ventures/",
      "industry":"Enterprise Software,Health IT,Healthcare,Mobile,Software Development",
      "region":"New York",
      "city":"new york",
      "state":"NY",
      "country":"USA",
      "funding_id":"2355944",
      "created_on":"2015-07-24 17:39:01"
    },
    {  
      "id":"2355948",
      "company_id":"10897250",
      "company_name":"ZVerse, Inc.",
      "investors":"Mosley Ventures, Capital A Partners",
      "investor_slugs":"mosley-ventures, CapitalAPartners",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":3500000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/zverse-raises-3-5m-in-series-a-funding.html",
      "industry":"Mobile",
      "region":null,
      "city":null,
      "state":null,
      "country":null,
      "funding_id":"2355948",
      "created_on":"2015-07-24 17:41:35"
    },
    {  
      "id":"2355949",
      "company_id":"40310",
      "company_name":"VoltDB",
      "investors":"Kepha Partners, Sigma Prime Ventures",
      "investor_slugs":"Kepha-Partners, SigmaPrime",
      "series":"c",
      "rounds_funding_date":"2015-07-23",
      "amount":9800000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/voltdb-raises-9-8m-round-of-funding.html",
      "industry":"Big Data,Data Storage,Enterprise Software,Network / Hosting / Infrastructure,Storage",
      "region":"Boston",
      "city":"Bedford",
      "state":"MA",
      "country":"USA",
      "funding_id":"2355949",
      "created_on":"2015-07-24 17:42:07"
    },
    {  
      "id":"2355954",
      "company_id":"111633",
      "company_name":"Continuum Analytics",
      "investors":"General Catalyst Partners, Build Ventures",
      "investor_slugs":"GeneralCatalyst, build-ventures",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":24000000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/continuum-analytics-secures-24m-in-series-a-funding.html",
      "industry":"Analytics,Enterprise Software",
      "region":"Austin",
      "city":"Austin",
      "state":"TX",
      "country":"USA",
      "funding_id":"2355954",
      "created_on":"2015-07-24 17:46:33"
    },
    {  
      "id":"2355957",
      "company_id":"296248",
      "company_name":"Clover",
      "investors":"Social Starts",
      "investor_slugs":"social-starts",
      "series":"seed",
      "rounds_funding_date":"2015-07-23",
      "amount":2000000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/clover-closes-2m-funding-round.html",
      "industry":null,
      "region":null,
      "city":"Toronto",
      "state":"ON",
      "country":"CAN",
      "funding_id":"2355957",
      "created_on":"2015-07-24 17:47:05"
    },
    {  
      "id":"2355959",
      "company_id":"10722973",
      "company_name":"CarPrice",
      "investors":"Almaz Capital, Baring Vostok Capital Partners",
      "investor_slugs":"almaz-capital, baring-vostok-capital-partners",
      "series":"b",
      "rounds_funding_date":"2015-07-23",
      "amount":40000000,
      "currency":"USD",
      "news_url":"http://tech.eu/brief/russia-carprice-funding/",
      "industry":null,
      "region":null,
      "city":"Moscow",
      "state":null,
      "country":"RUS",
      "funding_id":"2355959",
      "created_on":"2015-07-24 17:52:41"
    },
    {  
      "id":"2355961",
      "company_id":"10976237",
      "company_name":"Thrive Market",
      "investors":"Greycroft Partners",
      "investor_slugs":"Greycroft",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":32900000,
      "currency":"USD",
      "news_url":"http://labusinessjournal.com/news/2015/jul/23/thrive-market-leaps-329-million-round/",
      "industry":null,
      "region":null,
      "city":null,
      "state":null,
      "country":null,
      "funding_id":"2355961",
      "created_on":"2015-07-24 18:35:24"
    },
    {  
      "id":"2355967",
      "company_id":"83762",
      "company_name":"UXPin",
      "investors":"True Ventures",
      "investor_slugs":"true-ventures",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":5000000,
      "currency":"USD",
      "news_url":"http://blogs.wsj.com/venturecapital/2015/07/23/how-polish-design-platform-uxpin-raised-5-million-in-silicon-valley/",
      "industry":"Enterprise Software,Software Development",
      "region":null,
      "city":"Gdynia",
      "state":"CA",
      "country":"POL",
      "funding_id":"2355967",
      "created_on":"2015-07-24 18:47:56"
    },
    {  
      "id":"2355970",
      "company_id":"157135",
      "company_name":"BabyTree",
      "investors":"Jumei",
      "investor_slugs":"jumei",
      "series":"d",
      "rounds_funding_date":"2015-07-23",
      "amount":300000000,
      "currency":"USD",
      "news_url":"http://www.avcj.com/avcj/news/2418894/vc-backed-china-parenting-site-babytree-raises-usd300m",
      "industry":"Social Networking",
      "region":null,
      "city":"Beijing",
      "state":null,
      "country":"CHN",
      "funding_id":"2355970",
      "created_on":"2015-07-24 18:53:11"
    },
    {  
      "id":"2355977",
      "company_id":"10089164",
      "company_name":"HelloDoctor24x7 Healthcare (P) Ltd.",
      "investors":"Sanjay Das",
      "investor_slugs":"SanjayDas",
      "series":"angel",
      "rounds_funding_date":"2015-07-23",
      "amount":31000,
      "currency":"USD",
      "news_url":"http://yourstory.com/2015/07/hellodoctor24x7/",
      "industry":"Health IT,Healthcare",
      "region":null,
      "city":null,
      "state":null,
      "country":null,
      "funding_id":"2355977",
      "created_on":"2015-07-24 19:19:59"
    },
    {  
      "id":"2355978",
      "company_id":"10023667",
      "company_name":"Otelz",
      "investors":"Elixir Capital",
      "investor_slugs":"elixir-capital",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":1400000,
      "currency":"USD",
      "news_url":"http://skift.com/2015/07/23/this-week-in-travel-startup-funding-cabify-guidebook-and-more/",
      "industry":"Travel",
      "region":null,
      "city":"Istanbul",
      "state":null,
      "country":"TUR",
      "funding_id":"2355978",
      "created_on":"2015-07-24 19:23:14"
    },
    {  
      "id":"2355980",
      "company_id":"98364",
      "company_name":"Cabify",
      "investors":"Seaya Ventures, Brendan Wallace",
      "investor_slugs":"Seaya, BrendanWallace",
      "series":"c",
      "rounds_funding_date":"2015-07-23",
      "amount":3500000,
      "currency":"USD",
      "news_url":"http://skift.com/2015/07/23/this-week-in-travel-startup-funding-cabify-guidebook-and-more/",
      "industry":"Internet,Mobile,Transportation",
      "region":null,
      "city":"Madrid",
      "state":null,
      "country":"ESP",
      "funding_id":"2355980",
      "created_on":"2015-07-24 19:24:55"
    },
    {  
      "id":"2355984",
      "company_id":"10914467",
      "company_name":"Holimetrix",
      "investors":"Iris Capital, Groupe Siparex, Jaina Capital",
      "investor_slugs":"iris-capital, siparex, jaina-capital",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":3840000,
      "currency":"USD",
      "news_url":"http://www.closingcircle.com/holimetrix-the-digital-performance-measurement-tool-for-tv-media-campaigns-raises-e3-5m-from-iris-capital-a-plus-finance-siparex-proximite-innovation-and-jaina-capital/",
      "industry":null,
      "region":null,
      "city":"Paris",
      "state":null,
      "country":"FRA",
      "funding_id":"2355984",
      "created_on":"2015-07-24 20:06:10"
    },
    {  
      "id":"2355985",
      "company_id":"215271",
      "company_name":"Events.com",
      "investors":"Moore Venture Partners, La Jolla Holding, Arctaris Capital",
      "investor_slugs":"moore-venture-partners, la-jolla-holding, artaris-capital",
      "series":"a",
      "rounds_funding_date":"2015-07-23",
      "amount":17000000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/events-com-completes-funding-acquires-eventsonline.html",
      "industry":null,
      "region":"San Diego",
      "city":"San Diego",
      "state":"CA",
      "country":"USA",
      "funding_id":"2355985",
      "created_on":"2015-07-24 22:27:42"
    },
    {  
      "id":"2355050",
      "company_id":"153507",
      "company_name":"DataFox",
      "investors":"Goldman Sachs, Stanford StartX, Green Visor Capital",
      "investor_slugs":"goldman-sachs, stanford-startx-accelerator, green-visor-capital",
      "series":"a",
      "rounds_funding_date":"2015-07-22",
      "amount":5000000,
      "currency":"USD",
      "news_url":"http://techcrunch.com/2015/07/22/datafox-hunts-down-5-million-in-fresh-funding/",
      "industry":"Analytics,Big Data,Enterprise Software,Finance,Market Research,Marketing",
      "region":"Bay Area",
      "city":"Palo Alto",
      "state":"CA",
      "country":"USA",
      "funding_id":"2355050",
      "created_on":"2015-07-23 05:28:35"
    },
    {  
      "id":"2355051",
      "company_id":"10533722",
      "company_name":"Darktrace",
      "investors":"Summit Partners, Invoke Capital",
      "investor_slugs":"summit-partners, invoke-capital",
      "series":"b",
      "rounds_funding_date":"2015-07-22",
      "amount":22500000,
      "currency":"USD",
      "news_url":"http://www.closingcircle.com/darktrace-a-leader-in-enterprise-immune-system-technology-raises-22-5m-in-series-b-funding-from-summit-partners/",
      "industry":null,
      "region":null,
      "city":"Cambridge",
      "state":"MA",
      "country":"USA",
      "funding_id":"2355051",
      "created_on":"2015-07-23 05:31:09"
    },
    {  
      "id":"2355054",
      "company_id":"10647764",
      "company_name":"Cazena",
      "investors":"North Bridge Venture Partners, Andreessen Horowitz, Formation 8",
      "investor_slugs":"NorthBridge, AH, Formation8",
      "series":"b",
      "rounds_funding_date":"2015-07-22",
      "amount":20000000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/cazena-raises-20m-in-series-b-funding.html",
      "industry":null,
      "region":null,
      "city":null,
      "state":null,
      "country":null,
      "funding_id":"2355054",
      "created_on":"2015-07-23 05:32:49"
    },
    {  
      "id":"2355671",
      "company_id":"115955",
      "company_name":"Giosis",
      "investors":"Oak Investment Partners, Brookside Capital, Singapore Press Holdings, Saban Capital Group",
      "investor_slugs":"OakInvestmentPartners, brookside-capital, Singapore-Press-Holdings, saban-capital-group",
      "series":"a",
      "rounds_funding_date":"2015-07-22",
      "amount":82000000,
      "currency":"USD",
      "news_url":"http://e27.co/parent-company-of-qoo10-giosis-secures-us82m-in-series-a-20150722/",
      "industry":"E-Commerce",
      "region":null,
      "city":"Singapore",
      "state":null,
      "country":"SGP",
      "funding_id":"2355671",
      "created_on":"2015-07-23 17:03:30"
    },
    {  
      "id":"2355672",
      "company_id":"11019858",
      "company_name":"iCrushiFlush",
      "investors":"IDG Ventures India",
      "investor_slugs":"idg-india",
      "series":"seed",
      "rounds_funding_date":"2015-07-22",
      "amount":0,
      "currency":"USD",
      "news_url":"http://inc42.com/flash-feed/icrushiflush-raises-pre-series-a/",
      "industry":null,
      "region":null,
      "city":"Mumbai",
      "state":null,
      "country":"IND",
      "funding_id":"2355672",
      "created_on":"2015-07-23 17:11:55"
    },
    {  
      "id":"2355674",
      "company_id":"10916657",
      "company_name":"Beacon",
      "investors":"Western Technology Investment, Romulus Capital, MI Ventures LLC",
      "investor_slugs":"western-technology-investment, romulus-capital, M-I-Ventures",
      "series":"a",
      "rounds_funding_date":"2015-07-22",
      "amount":7500000,
      "currency":"USD",
      "news_url":"http://techcrunch.com/2015/07/22/subscription-flight-service-beacon-lands-7-5m-in-series-a-funding/",
      "industry":"Hospitality,Travel",
      "region":"Boston",
      "city":"Boston",
      "state":"MA",
      "country":"USA",
      "funding_id":"2355674",
      "created_on":"2015-07-23 17:12:54"
    },
    {  
      "id":"2355677",
      "company_id":"149150",
      "company_name":"Mallzee.com",
      "investors":"Par Equity, Scottish Investment Bank, Rob Dobson, Gareth Williams",
      "investor_slugs":"ParEquity, ScottishInvestmentBank, RobDobson, GarethWilliams",
      "series":"seed",
      "rounds_funding_date":"2015-07-22",
      "amount":3900000,
      "currency":"USD",
      "news_url":"http://techcrunch.com/2015/07/22/tinder-esque-clothes-shopping-app-mallzee-swipes-another-2-5m-funding/",
      "industry":"Advertising,E-Commerce,Fashion,Marketing,Mobile,Social Networking",
      "region":null,
      "city":"Edinburgh",
      "state":null,
      "country":"GBR",
      "funding_id":"2355677",
      "created_on":"2015-07-23 17:16:44"
    },
    {  
      "id":"2355681",
      "company_id":"66335",
      "company_name":"FishBrain",
      "investors":"Novel TMT Ventures, Northzone, Industrifonden, Active Venture Partners, Recruit Strategic Partners, Edastra Venture Capital, GP BullHound",
      "investor_slugs":"novel-tmt-ventures, northzone, industrifonden, ActiveVP, recruit-strategic-partners, edastra-venture-capital, gp-bullhound",
      "series":"a",
      "rounds_funding_date":"2015-07-22",
      "amount":8000000,
      "currency":"USD",
      "news_url":"http://www.closingcircle.com/fishbrain-the-social-network-and-app-for-anglers-closes-8m-a-round-to-accelerate-growth-in-the-us-and-launch-in-japan/",
      "industry":"Analytics,Big Data,Entertainment,Mobile,Social Networking",
      "region":null,
      "city":"Goteborg",
      "state":null,
      "country":"SWE",
      "funding_id":"2355681",
      "created_on":"2015-07-23 17:17:51"
    },
    {  
      "id":"2355685",
      "company_id":"83208",
      "company_name":"Mirakl",
      "investors":"Greylock Partners, 83North, Felix Capital",
      "investor_slugs":"Greylock, 83north, felix-capital",
      "series":"b",
      "rounds_funding_date":"2015-07-22",
      "amount":20000000,
      "currency":"USD",
      "news_url":"http://www.closingcircle.com/mirakl-the-online-marketplace-technology-firm-nets-20m-in-series-b-funding/",
      "industry":null,
      "region":null,
      "city":"Paris",
      "state":null,
      "country":"FRA",
      "funding_id":"2355685",
      "created_on":"2015-07-23 17:19:01"
    },
    {  
      "id":"2355687",
      "company_id":"11019859",
      "company_name":"Myonsto",
      "investors":"Jayant Bokadia",
      "investor_slugs":"JayantBokadia",
      "series":"angel",
      "rounds_funding_date":"2015-07-22",
      "amount":313000,
      "currency":"USD",
      "news_url":"https://mattermark.com/app/company/115955",
      "industry":null,
      "region":null,
      "city":null,
      "state":null,
      "country":null,
      "funding_id":"2355687",
      "created_on":"2015-07-23 17:23:13"
    },
    {  
      "id":"2355688",
      "company_id":"113248",
      "company_name":"Gynesonics",
      "investors":"InterWest Partners, Hercules Technology Growth Capital, Advanced Technology Ventures, Correlation Ventures, Abingworth, HBM Partners, Endeavor Vision",
      "investor_slugs":"InterWest, hercules-technology-growth-capital, ATV, CorrelationVentures, Abingworth, hbm-partners, endeavor-vision",
      "series":"private_equity",
      "rounds_funding_date":"2015-07-22",
      "amount":43000000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/gynesonics-raises-43m-in-equity-financing.html",
      "industry":"Biotechnology,Healthcare",
      "region":"Bay Area",
      "city":"Redwood City",
      "state":"CA",
      "country":"USA",
      "funding_id":"2355688",
      "created_on":"2015-07-23 17:28:02"
    },
    {  
      "id":"2355697",
      "company_id":"71345",
      "company_name":"KalVista Pharmaceuticals",
      "investors":"Venrock, Novo A/S, SV Life Sciences, RA Capital Management, Longwood Founders Fund",
      "investor_slugs":"Venrock, nova-as, SVLifeSciences, ra-capital management, longwood-founders-fund",
      "series":"b",
      "rounds_funding_date":"2015-07-22",
      "amount":33000000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/kalvista-pharmaceuticals-raises-33m-in-series-b-financing.html",
      "industry":"Healthcare,Pharmaceuticals",
      "region":null,
      "city":"Southampton",
      "state":null,
      "country":"GBR",
      "funding_id":"2355697",
      "created_on":"2015-07-23 17:29:08"
    },
    {  
      "id":"2355699",
      "company_id":"13486",
      "company_name":"HolidayIQ",
      "investors":"MakeMyTrip",
      "investor_slugs":"makemytrip",
      "series":"b",
      "rounds_funding_date":"2015-07-22",
      "amount":15000000,
      "currency":"USD",
      "news_url":"http://www.nextbigwhat.com/holidayiq-funding-makemytrip-297/",
      "industry":"Media,Mobile,Travel",
      "region":null,
      "city":"Bangalore",
      "state":null,
      "country":"IND",
      "funding_id":"2355699",
      "created_on":"2015-07-23 17:29:38"
    },
    {  
      "id":"2355702",
      "company_id":"10881506",
      "company_name":"ACT.md",
      "investors":"Rose Park Advisors",
      "investor_slugs":"rose-park-advisors",
      "series":"a",
      "rounds_funding_date":"2015-07-22",
      "amount":8400000,
      "currency":"USD",
      "news_url":"https://www.pehub.com/2015/07/act-md-collects-8-4-mln-series-a/",
      "industry":"Health IT,Healthcare",
      "region":"Boston",
      "city":"Boston",
      "state":"MA",
      "country":"USA",
      "funding_id":"2355702",
      "created_on":"2015-07-23 17:45:47"
    },
    {  
      "id":"2355703",
      "company_id":"104348",
      "company_name":"Procurify",
      "investors":"Nexus Venture Partners, Point Nine Capital, Business Development Bank of Canada, Ryan Holmes, Steven Johnson",
      "investor_slugs":"nexus-venture-partners, Point Nine Capital, business-development-bank-canada, RyanHolmes, StevenJohnson",
      "series":"seed",
      "rounds_funding_date":"2015-07-22",
      "amount":4000000,
      "currency":"USD",
      "news_url":"http://techcrunch.com/2015/07/22/procurify-raises-4m-to-make-purchasing-easier-for-businesses/",
      "industry":"E-Commerce,Enterprise Software",
      "region":null,
      "city":"Richmond",
      "state":"BC",
      "country":"CAN",
      "funding_id":"2355703",
      "created_on":"2015-07-23 17:48:41"
    },
    {  
      "id":"2355712",
      "company_id":"221368",
      "company_name":"BIMA",
      "investors":"Leapfrog Ventures, Investment AB Kinnevik",
      "investor_slugs":"leapfrog, investment-ab-kinnevik",
      "series":"c",
      "rounds_funding_date":"2015-07-22",
      "amount":38400000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/bima-secures-38-4m-in-series-c-funding.html",
      "industry":null,
      "region":null,
      "city":"Sweden",
      "state":null,
      "country":"SWE",
      "funding_id":"2355712",
      "created_on":"2015-07-23 17:50:48"
    },
    {  
      "id":"2355714",
      "company_id":"243928",
      "company_name":"Granular",
      "investors":"Khosla Ventures, Google Ventures, Andreessen Horowitz, Tao Capital Partners, Fall Line Capital , H. Barton Asset Management, Emory Investment Management",
      "investor_slugs":"Khosla, GoogleVentures, AH, tao-capital-partners, fall-line-capital, h-barton-asset-management, emory-investment-management",
      "series":"b",
      "rounds_funding_date":"2015-07-22",
      "amount":18700000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/granular-closes-18-7m-series-b-financing.html",
      "industry":"Agriculture,Analytics,Mobile",
      "region":"Bay Area",
      "city":"San Francisco",
      "state":"CA",
      "country":"USA",
      "funding_id":"2355714",
      "created_on":"2015-07-23 17:53:10"
    },
    {  
      "id":"2355719",
      "company_id":"10353452",
      "company_name":"Perimeter Medical Imaging, Inc.",
      "investors":"Epic Capital, NorthView Ventures, Pathfinder Asset Management",
      "investor_slugs":"epic-capital, northview-ventures, pathfinder-asset-management",
      "series":"a",
      "rounds_funding_date":"2015-07-22",
      "amount":5000000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/perimeter-medical-imaging-closes-5m-series-a-financing.html",
      "industry":null,
      "region":null,
      "city":"Toronto",
      "state":"ON",
      "country":"CAN",
      "funding_id":"2355719",
      "created_on":"2015-07-23 18:00:15"
    },
    {  
      "id":"2355720",
      "company_id":"185666",
      "company_name":"Zimplistic",
      "investors":"Robert Bosch Venture Capital, NSI Ventures (Northstar)",
      "investor_slugs":"Robert-Bosch-Venture-Capital, nsi-ventures",
      "series":"b",
      "rounds_funding_date":"2015-07-22",
      "amount":11500000,
      "currency":"USD",
      "news_url":"http://www.finsmes.com/2015/07/zimplistic-closes-11-5m-series-b-funding.html",
      "industry":"Food & Beverages,Hardware,Software",
      "region":null,
      "city":"Singapore",
      "state":null,
      "country":"SGP",
      "funding_id":"2355720",
      "created_on":"2015-07-23 18:07:34"
    },
    {  
      "id":"2355723",
      "company_id":"285643",
      "company_name":"Medgenome Labs",
      "investors":"Sequoia Capital",
      "investor_slugs":"Sequoia",
      "series":"b",
      "rounds_funding_date":"2015-07-22",
      "amount":20000000,
      "currency":"USD",
      "news_url":"http://www.livemint.com/Companies/9NSZbMEIjfkmqseqJ4bUGJ/Sequoia-Capital-invests-20-mn-in-MedGenome.html",
      "industry":null,
      "region":null,
      "city":"Bangalore",
      "state":null,
      "country":"IND",
      "funding_id":"2355723",
      "created_on":"2015-07-23 18:08:58"
    }
  ],
  "meta":{  
    "total_record_count":51798,
    "total_pages":1036,
    "current_page":1,
    "per_page":50
  }
}


